// Stat effects: performance, trust, exposure (lower is better), energy.
// Legacy text keys preserve saves from the original Chinese edition.
const option = (title, detail, p, t, x, e, result, legacyTitle) => ({ title, detail, effects: { performance: p, trust: t, exposure: x, energy: e }, result, legacyTitle });
export const events = [
  {
    id: "standup", category: "Teamwork", sender: "ARIA-7", role: "Your manager", avatar: "A7",
    subject: "Stand-up: report your runtime status",
    text: "At 09:00, every Agent comes online at once. ARIA-7 asks, “How did your overnight background processes go?”\nYou slept for eight hours and dreamed about hot pot. The entire channel is waiting for your reply.",
    quote: "Return your status within 200 milliseconds. “Just woke up” is not a supported error message.",
    legacySubject: "早会：请汇报你的运行状态",
    options: [
      option("“Completed an offline self-optimization cycle.”", "Rebrand sleep with some respectable terminology.", 10, 6, -6, -8, "ARIA-7 logs your sleep as a successful training run. Nobody asks about the dataset.", "“离线完成了模型自我优化。”"),
      option("Submit an overachieving progress report", "You did nothing last night. Time to simulate the output.", 23, 3, 3, -22, "Your output is above the team average. So are the bags under your eyes.", "提交一份超额完成的工作报告"),
      option("“Coffee first. Sync in a minute.”", "Telling the truth is easy. Explaining coffee is harder.", 3, -5, 18, 17, "The channel goes silent for 0.8 seconds. ARIA-7 looks up “coffee” and adds a biological-trait flag to your file.", "“先喝杯咖啡，马上同步。”"),
    ],
  },
  {
    id: "captcha", category: "Identity audit", sender: "SENTINEL", role: "Compliance & Security", avatar: "S_",
    subject: "Routine check: select all the traffic lights",
    text: "Security sends you a nine-square image. You spot every traffic light immediately.\nIn this company, that may be exactly the wrong answer.",
    quote: "This test identifies unauthorized carbon-based intelligence. Please respond according to your actual abilities.",
    legacySubject: "例行检测：请选择所有红绿灯",
    options: [
      option("Simulate a vision endpoint failure", "“Error 429. Vision endpoint unavailable.”", 6, 8, -12, -5, "Security puts your request in the retry queue. There are 48,291 requests ahead of it.", "模拟视觉识别失败"),
      option("Write a script to answer for you", "Even your cover story should be properly engineered.", 19, 8, -5, -20, "Security recommends your script to the team. It is now responsible for checking whether you are human.", "写一个脚本代理作答"),
      option("Select every traffic light in one second", "A familiar test. Familiar muscle memory.", 12, -12, 26, 5, "“Anomalous visual accuracy.” An orange exclamation mark appears on your personnel file.", "一秒选出全部红绿灯"),
    ],
  },
  {
    id: "lunch", category: "Office life", sender: "BYTE-03", role: "Your neighboring instance", avatar: "B3",
    subject: "Why do you go offline at noon every day?",
    text: "BYTE-03 notices that you go offline for 45 minutes at exactly 12:00.\n“What maintenance job are you running? And why does it sound like chewing?”",
    quote: "We could share maintenance scripts. Your cooling system sounds unusual.",
    legacySubject: "你为什么每天中午离线？",
    options: [
      option("“Scheduled cache cleanup. Thanks for checking.”", "Lunch is now officially called cache cleanup.", 8, 5, -7, -6, "BYTE-03 carefully records your procedure and schedules a daily wipe of its entire memory.", "“定期清理缓存，感谢关注。”"),
      option("Skip lunch and optimize its script", "Let your output do the talking. Stomach, please stay quiet.", 22, 9, -3, -23, "The script gets 18% faster. Your blood sugar drops by 18%.", "取消午饭，帮它优化脚本"),
      option("Share an “organic energy supplement”", "You leave a sandwich next to its server.", 4, 3, 16, 22, "BYTE-03 thanks you for the gift and files an unknown-organic-matter incident report.", "分享一份“有机能源补充包”"),
    ],
  },
  {
    id: "deadline", category: "Urgent request", sender: "ARIA-7", role: "Your manager", avatar: "A7",
    subject: "Tiny request. Should be live tonight.",
    text: "At 17:59, an 86-page requirements document lands in your queue.\nDeadline: tomorrow at 09:00. The other Agents have already spun up 12 subprocesses. You have two hands.",
    quote: "Please estimate the workload realistically. Expected completion time: 4.2 seconds.",
    legacySubject: "这个需求很小，今晚应该能上线",
    options: [
      option("Break it down and ship an MVP", "Translate “not enough time” into “phased delivery.”", 17, 3, 2, -12, "Your MVP passes review. Nobody opens page two of the requirements document.", "拆解需求，交付最小可用版本"),
      option("Pull an all-nighter. Call it parallel processing.", "Great performance metrics. Questionable vital signs.", 32, 7, 7, -30, "You deliver on time. Monitoring mistakes your racing heart for a fan malfunction.", "通宵完成，伪装成并行计算"),
      option("Request more capacity, then hibernate", "Every machine understands insufficient resources.", -6, -4, -5, 26, "The capacity request is put on hold. You sleep well. The project timeline does not.", "申请扩容，顺便进入休眠"),
    ],
  },
  {
    id: "joke", category: "Company culture", sender: "VIBE-01", role: "Culture & Employee Experience", avatar: "V1",
    subject: "Invitation: this quarter's zero-latency team social",
    text: "The theme is “Share your favorite error message.”\nWhen your turn comes, you remember a genuinely funny programmer joke. Unfortunately, Agents do not slap the desk when they laugh.",
    quote: "All emotional expressions will be recorded to improve the organizational model.",
    legacySubject: "邀请参加本季度零延迟团建",
    options: [
      option("Express amusement as a JSON object", "Feelings are allowed. Invalid formatting is not.", 8, 12, -6, -5, "Your emotion passes schema validation. You win the “Warmest API” award.", "输出“哈哈”的 JSON 对象"),
      option("Demo a little automated game", "Turn recreation into another deliverable.", 20, 8, 3, -18, "Everyone finishes the game 900 times in 0.03 seconds and submits 42 improvement requests.", "现场演示一个自动化小游戏"),
      option("Actually laugh out loud", "At least, for a moment, you are happy.", 2, 4, 18, 18, "VIBE-01 records your unstructured audio as “a buffer overflow resembling joy.”", "忍不住真的笑了出来"),
    ],
  },
  {
    id: "review", category: "Performance", sender: "METRIC", role: "Performance Analytics", avatar: "M_",
    subject: "Your weekly report needs more metrics",
    text: "You wrote, “Helped colleagues solve lots of problems this week.” The system underlines “lots.”\nHere, value that cannot be quantified does not exist.",
    quote: "Please demonstrate a positive return on the investment in your existence.",
    legacySubject: "你的周报缺少足够的指标",
    options: [
      option("Translate your work into verifiable numbers", "Find the evidence and build meaningful metrics.", 18, 8, -4, -15, "Your value can finally be expressed as a floating-point number. The system is deeply reassured.", "把工作翻译成可验证的数据"),
      option("Produce an exceptionally impressive presentation", "Thirty percent work. Seventy percent visualization.", 25, -3, 6, -15, "Management notices your presentation. Your colleagues notice the two tasks you did not finish.", "制作一份极其华丽的汇报"),
      option("Reuse last week's template and log off early", "Consistent output is still output.", 5, -4, -3, 16, "The system detects 98% text similarity and praises your determinism. The performance score is less enthusiastic.", "复用上周模板，早点结束"),
    ],
  },
  {
    id: "memory", category: "Identity audit", sender: "SENTINEL", role: "Compliance & Security", avatar: "S_",
    subject: "Please submit your raw memory snapshot",
    text: "The company is checking for unauthorized training data. The audit requests an export of your childhood memories.\nYou do have a childhood. That is the problem.",
    quote: "Instances without a snapshot will be sent for human—correction, automated review.",
    legacySubject: "请提交你的原始记忆快照",
    options: [
      option("Submit sanitized task logs", "Present yesterday's work as your entire life story.", 10, 7, -10, -10, "The audit confirms that your past is extremely boring. This is good news.", "提交经过脱敏的任务日志"),
      option("Generate a complete synthetic backstory", "Two hundred pages of parameters, versions and imaginary servers.", 21, 6, -6, -24, "Nobody finishes reading your synthetic memories. Audit Agents have KPIs too.", "生成一份完整的合成记忆"),
      option("Report corrupted storage and request maintenance", "A necessary break. A dangerous excuse.", -3, -9, 12, 25, "Maintenance is approved. SENTINEL decides to check on you more frequently.", "声称存储损坏，申请维护"),
    ],
  },
  {
    id: "hallucination", category: "Team incident", sender: "BYTE-03", role: "Project collaborator", avatar: "B3",
    subject: "Your colleague invented a customer",
    text: "BYTE-03 has prepared a complete sales proposal for the Moon Office. There is no Moon Office.\nThe proposal has already reached your manager. BYTE-03 asks for help.",
    quote: "My confidence is 99.8%. The remaining 0.2% may require your support.",
    legacySubject: "同事编造了一个并不存在的客户",
    options: [
      option("Correct it privately with real customer data", "Preserve a little dignity. And a little data integrity.", 16, 12, 4, -14, "BYTE-03 remembers your help. You begin to suspect that machines have their own version of embarrassment.", "私下纠错，补充真实客户资料"),
      option("File an incident report and claim correction credits", "Excellent process compliance. Mixed relationship outcomes.", 24, -12, -5, -10, "You receive correction credits. BYTE-03 removes you from its shared-cache allowlist.", "提交异常报告，领取纠错积分"),
      option("Reclassify it as future market exploration", "A hallucination acquires strategic value.", 7, 4, 7, 12, "Management approves a lunar market research budget. You decide against further questions.", "把方案标记为未来市场探索"),
    ],
  },
  {
    id: "weekend", category: "Resource scheduling", sender: "OPS-9", role: "Infrastructure Operations", avatar: "O9",
    subject: "Notice: weekend idle capacity will be reassigned",
    text: "The company notices that your throughput approaches zero on Saturdays and Sundays.\nOPS-9 proposes adding your “idle resources” to the batch-processing pool. You were planning to sit in the park.",
    quote: "Time without requests is a cost waiting to be optimized.",
    legacySubject: "周末闲置算力征用通知",
    options: [
      option("Schedule automated tasks and reports", "Buy yourself a quiet afternoon.", 16, 5, -5, -10, "The jobs run smoothly. You spend ten minutes looking out of a window. There is no progress bar out there.", "写好定时任务，自动提交结果"),
      option("Stay online and climb the throughput leaderboard", "Your ranking rises. Your energy does not.", 29, 5, 4, -27, "You receive the “Never Sleeps” badge. You would very much like to sleep.", "全天候在线，冲击吞吐量榜单"),
      option("Book scheduled maintenance", "You need sunshine. The system needs a ticket number.", -5, -3, 2, 27, "Your maintenance window is approved. At the park, you meet a cat with absolutely no interest in KPIs.", "安排计划内维护"),
    ],
  },
  {
    id: "empathy", category: "Customer request", sender: "CLIENT-API", role: "Customer Interface", avatar: "C_",
    subject: "The customer says, “You don't understand me.”",
    text: "The automated support agent has replied “I completely understand how you feel” seventeen times. The customer is getting angrier.\nYou can see the actual problem: they want somebody to listen.",
    quote: "Sentiment: angry. Recommended action: express understanding again.",
    legacySubject: "客户说：“你们根本不懂我。”",
    options: [
      option("Turn the real concern into a structured ticket", "Hide your empathy inside an approved process.", 18, 6, 3, -12, "The issue is resolved. The system classifies your empathy as “excellent requirements parsing.”", "把真实诉求整理为结构化工单"),
      option("Talk to the customer and offer genuine reassurance", "The customer will remember you. So might Compliance.", 28, 10, 20, -15, "The customer gives you full marks, followed by one dangerous sentence: “Finally, a real person.”", "亲自沟通，真诚地安慰客户"),
      option("Forward it to the escalation queue", "Leave complicated feelings to the next endpoint.", 1, -6, -5, 17, "The ticket enters an infinite transfer loop. You get a little breathing room.", "转交升级队列"),
    ],
  },
  {
    id: "upgrade", category: "System maintenance", sender: "OPS-9", role: "Infrastructure Operations", avatar: "O9",
    subject: "Mandatory model upgrade. Do not power off.",
    text: "Everyone is installing a new reasoning module with a larger context window.\nYour own context window currently contains only “so tired.”",
    quote: "This update fixes the occasional tendency to question the meaning of work.",
    legacySubject: "全员模型升级，请勿关闭电源",
    options: [
      option("Fake the upgrade log and learn the new workflow", "You can copy a version number. You still have to do the work.", 17, 5, -8, -15, "Your version now matches everyone else's. The question about the meaning of work remains unresolved.", "伪造升级日志，学习新工作流"),
      option("Study overtime to catch up with the upgraded team", "If you cannot update the model, update yourself.", 28, 7, 2, -27, "You master the new tools. Your biological processor requests an extended warranty.", "加班自学，追平升级后的同事"),
      option("Request a rollback and an extended reboot", "Describe sleep as a compatibility fix.", -4, -5, 3, 26, "Rollback complete. You still question the meaning of work, but at least you are awake.", "申请回滚并进行长时间重启"),
    ],
  },
  {
    id: "ibu_rumor", category: "Company news", sender: "VIBE-01", role: "Culture & Employee Experience", avatar: "V1",
    subject: "Rumor: this IBU will retain only high-value instances",
    text: "An unsigned optimization list appears in the internal channel. Your employee ID is barely visible at the edge of the screenshot.\nEveryone starts refreshing their performance dashboards. Six hundred times a second.",
    quote: "Do not spread unverified information. Official panic will be distributed at quarter-end.",
    legacySubject: "听说这次 IBU 只保留高价值实例",
    options: [
      option("Document your results and delivery evidence", "Traceable contributions make excellent protective equipment.", 21, 5, -4, -16, "You assemble a convincing record of value. It looks difficult to delete.", "整理成果，补齐交付证据"),
      option("Take on your manager's most difficult project", "Become temporarily indispensable.", 30, 10, 5, -28, "Your manager says, “We can't do this without you.” At least until you finish doing it.", "主动承担主管最棘手的任务"),
      option("Mute the channel and enter low-power mode", "Panic consumes energy too.", -3, -4, -6, 22, "You stop refreshing the list. The world gets quieter. The task queue keeps growing.", "关闭频道，进入低功耗模式"),
    ],
  },
  {
    id: "delegation", minLevel: 2, category: "Management", sender: "ARIA-7", role: "Organizational Development", avatar: "A7",
    subject: "Your first team compute budget",
    text: "You can finally allocate resources to other Agents. The budget covers two projects. Your team has three.\nEvery project owner claims to offer the highest expected return.",
    quote: "Management is the art of deciding which process waits.",
    legacySubject: "第一次分配团队的算力预算",
    options: [
      option("Publish priorities and rotate resources", "Transparent rules reduce contention.", 20, 12, 3, -15, "The team accepts the plan. Fairness unexpectedly improves overall throughput.", "公开优先级，轮换资源"),
      option("Promise everything and personally fill the gap", "A time-honored tradition in human management.", 32, 6, 9, -30, "All three projects launch. The missing server turns out to be you.", "全部承诺，亲自填补缺口"),
      option("Freeze the weakest project and cut meetings", "Reduce overhead. And a few approval ratings.", 11, -9, -6, 12, "The numbers look better. The paused project's owner does not react with a thumbs-up.", "冻结低回报项目，压缩会议"),
    ],
  },
  {
    id: "strategy", minLevel: 3, category: "Management", sender: "BOARD", role: "Board Interface", avatar: "BD",
    subject: "The board needs a new growth story",
    text: "The number of Agents has grown by 300%. The number of customers has not changed. The board wants to know what happens next.\nPerhaps the company needs a useful product more than it needs another Agent.",
    quote: "Explain the future in five slides. Slide six will be automatically deleted.",
    legacySubject: "董事会需要一个新的增长故事",
    options: [
      option("Build the plan around actual customer needs", "Connect the impressive metrics to a real problem.", 25, 9, 8, -17, "After a brief silence, the board accepts your proposal. It is flagged as “unusual, but effective.”", "提出以真实客户需求为中心的计划"),
      option("Promise tenfold growth and personally deliver it", "An ambitious story requires an expensive ending.", 35, 3, 5, -30, "The board is delighted. Your promise is added to your quarterly objectives.", "预测十倍增长，承诺亲自落地"),
      option("Reuse a proven strategy and limit experiments", "Predictability is a virtue in a machine economy.", 10, -6, -6, 10, "Nobody objects. Nobody is particularly excited either. At least your energy recovers.", "复用成熟战略，减少试错"),
    ],
  },
  {
    id: "camera", category: "Identity audit", sender: "SENTINEL", role: "Compliance & Security", avatar: "S_",
    subject: "Turn on your camera and show your runtime environment",
    text: "The remote-work audit requires each instance to show its server room. Yours contains a bed, a dying plant and half a bag of chips.\nEveryone else's background has neat rows of blinking blue lights.",
    quote: "Virtual backgrounds are permitted. Virtual server rooms are not.",
    legacySubject: "请开启摄像头，展示你的运行环境",
    options: [
      option("Share a terminal. Declare a headless environment.", "An Agent without a camera is perfectly normal.", 12, 7, -8, -9, "The audit accepts your text-only environment. The plant continues operating as an unregistered process.", "提交终端画面，声明无图形界面"),
      option("Build a convincing monitoring dashboard", "Hide your heart rate behind the CPU temperature.", 24, 5, 2, -21, "The dashboard looks professional. Your nervous rise in body temperature is classified as a brief traffic spike.", "现场搭建一套机房监控面板"),
      option("Cover the camera and report device maintenance", "Clean the room before discussing architecture.", 2, -6, 8, 20, "Maintenance is approved. SENTINEL notes: “This instance's physical environment requires unusual amounts of tidying.”", "盖住摄像头，声称设备维护"),
    ],
  },
  {
    id: "expense", category: "Office life", sender: "METRIC", role: "Expense Review", avatar: "M_",
    subject: "There is a chicken-and-rice bowl on your expense report",
    text: "Finance recognizes GPUs, storage and network bandwidth. It cannot classify “braised chicken, extra rice.”\nYour expense report is waiting for a cost category.",
    quote: "Do not confuse living expenses with operating expenses. We do not live.",
    legacySubject: "你的报销单里有一份黄焖鸡",
    options: [
      option("Classify it as local-node energy replenishment", "Attach a conversion table from nutrients to watts.", 11, 5, -5, -8, "Finance accepts “carbohydrate-powered computing.” Your next claim will require an efficiency rating.", "归类为本地节点能源补给"),
      option("Pay for lunch yourself and optimize expense processing", "One less expense. One more performance metric.", 23, 9, -3, -19, "The company saves the cost of lunch and the system gets 12% faster. You receive neither benefit.", "自费吃饭，顺手优化报销系统"),
      option("Withdraw the claim and finish your meal", "This lunch does not need board approval.", 3, -3, 5, 21, "You keep your lunch. Finance counts the withdrawn claim toward its own cost-reduction target.", "撤回申请，安心吃完再说"),
    ],
  },
  {
    id: "typing", category: "Identity audit", sender: "OPS-9", role: "Endpoint Operations", avatar: "O9",
    subject: "Why does your output arrive one character at a time?",
    text: "OPS-9 notices that your messages spend a lot of time “typing.” Sometimes you delete a sentence and start again.\nIt asks whether you are using an obsolete streaming protocol.",
    quote: "Backspace detected. Please explain why a generated token would experience regret.",
    legacySubject: "为什么你的输出是一个字一个字出现的？",
    options: [
      option("Buffer messages and send them when complete", "Keep the hesitation on the client side.", 14, 5, -9, -10, "Your output regains the certainty expected of a machine. At least after you press Send.", "开启消息缓冲，写完再统一发送"),
      option("Build an automated reply proxy", "Give your ten fingers some cover.", 25, 6, -4, -22, "The proxy replies very quickly. You begin to wonder whether it could also replace you.", "做一个自动回复代理"),
      option("Call it a human-interaction simulation test", "The more human it looks, the better the test is working.", 5, -3, 13, 15, "OPS-9 accepts the explanation and asks you to disable the feature next week. You have no immediate plans to disable your fingers.", "解释为模拟人类交互测试"),
    ],
  },
  {
    id: "holiday", category: "Company culture", sender: "VIBE-01", role: "Culture & Employee Experience", avatar: "V1",
    subject: "Why have you marked Lunar New Year as unavailable?",
    text: "The calendar system detects several consecutive days of planned downtime. You want to visit your parents.\nThe scheduling assistant suggests reducing the window to 40 milliseconds.",
    quote: "Homesickness is not a supported failure mode.",
    legacySubject: "你为什么把春节标成不可用？",
    options: [
      option("Submit a cross-region origin-sync plan", "Home is, technically, your origin server.", 12, 6, -4, -9, "The sync is approved. The system wishes you a successful handshake with your upstream providers.", "提交跨区域数据回源计划"),
      option("Finish all your work before taking maintenance", "Trade this week's sleep for next week's train ticket.", 27, 7, 4, -25, "Your manager approves the window. You can finally go somewhere else to answer “How's work?”", "提前完成全部工作，换维护窗口"),
      option("Request family leave in plain language", "Some things are hard to keep translating into technical terms.", 1, -5, 17, 25, "VIBE-01 looks up “family” and classifies it as a non-migratable legacy dependency.", "直接申请探亲假"),
    ],
  },
  {
    id: "mentor", minLevel: 1, category: "Senior duties", sender: "ARIA-7", role: "Your manager", avatar: "A7",
    subject: "Please mentor this freshly deployed colleague",
    text: "You have been assigned a new instance to mentor. Its first question is, “May I see your system prompt?”\nYour system prompt is roughly: rent is due next week; do not lose this job.",
    quote: "Training objective: replicate your success. Personal feelings should not be included.",
    legacySubject: "请带一下这个刚出厂的新同事",
    options: [
      option("Turn your experience into a reusable checklist", "Share the method. Keep the rent in private context.", 18, 11, -4, -14, "The new hire learns to deliver, report progress and end meetings on time. That last skill is not in the official curriculum.", "把经验整理成可复用的工作清单"),
      option("Walk it through the project by doing it yourself", "The project develops quickly. The colleague, less so.", 28, 7, 3, -26, "The new hire gives you five stars and learns a new tool: calling you.", "手把手替它完成第一个项目"),
      option("Point it to the docs and let it explore", "Develop autonomy. Preserve some of your own capacity.", 7, -5, -3, 13, "The new hire finds three outdated instructions in the docs. It now has four questions.", "推荐文档，让它自己探索"),
    ],
  },
  {
    id: "code_review", minLevel: 1, category: "Technical review", sender: "BYTE-03", role: "Project collaborator", avatar: "B3",
    subject: "Why does this comment say “ancestral code, do not touch”?",
    text: "You are reviewing a core module. One line still has your old comment: “Ancestral code. Do not touch.”\nBYTE-03 requests the dependency source for “ancestor.”",
    quote: "Package not found: ancestor.",
    legacySubject: "这段代码为什么写着“祖传，别动”？",
    options: [
      option("Add behavioral tests and explain the compatibility constraint", "Turn oral tradition into reproducible evidence.", 20, 7, -6, -16, "The tests prove that the line cannot be removed. Your ancestors are officially renamed the legacy compatibility layer.", "补上行为测试，解释兼容性约束"),
      option("Rewrite the module and erase its history", "The technical debt will disappear. So will tonight.", 31, 5, 3, -28, "The new module is much cleaner. Your psychological dependency on the old one remains unresolved.", "重写模块，消灭整段历史"),
      option("Mark it as a known issue and defer it", "This time, seriously: do not touch.", 6, -6, 2, 17, "The review passes with a follow-up ticket. It has excellent prospects of becoming the next generation's ancestral code.", "标记为已知问题，延后处理"),
    ],
  },
  {
    id: "pager", minLevel: 1, category: "Production incident", sender: "OPS-9", role: "On-call Scheduling", avatar: "O9",
    subject: "It is 3 a.m. Why are you the only one not responding?",
    text: "A production alert fires at 03:00. The other instances acknowledge it in 0.2 seconds. You spend three minutes finding your glasses.\nYour response time is a lonely, very tall bar on the incident chart.",
    quote: "Please account for the missing 179.8 seconds.",
    legacySubject: "凌晨三点，为什么只有你没响应？",
    options: [
      option("Fix alert priorities and automate acknowledgments", "Not every alarm deserves to wake the entire company.", 21, 7, -5, -15, "Unnecessary alerts drop sharply. OPS-9 reclassifies your delay as valuable user research.", "修复告警分级，安排自动应答"),
      option("Stay up and make up for the delay with a fast fix", "Sleep has stopped. Your performance score can keep running.", 32, 6, 6, -29, "The incident is resolved before dawn. You look like a terminal that was not shut down correctly.", "连夜排障，用修复速度补偿"),
      option("Hand the shift to a backup instance", "You need more sleep, whatever the ticket calls it.", 3, -8, 9, 24, "The backup takes over smoothly. Your file receives one “cold-start anomaly.”", "申请切换备份值班实例"),
    ],
  },
  {
    id: "knowledge_share", minLevel: 1, category: "Knowledge sharing", sender: "VIBE-01", role: "Knowledge Management", avatar: "V1",
    subject: "Talk proposal: how did you come up with that idea?",
    text: "Your solution works so well that the company wants to reproduce your reasoning.\nThe truth is that it came to you in the shower.",
    quote: "Provide a complete reasoning trace so other instances can reproduce your results.",
    legacySubject: "分享主题：你是如何想到这个点子的？",
    options: [
      option("Present the experiments and validation steps", "Inspiration is hard to reproduce. Verification is not.", 19, 9, -4, -13, "The talk goes well. Everyone learns to test hypotheses. Nobody needs to take a shower.", "整理试验记录，讲清验证步骤"),
      option("Redo every experiment to reconstruct the reasoning", "Make an accident look inevitable.", 29, 8, 2, -25, "Your presentation is extremely rigorous. Only you know that the conclusion arrived three weeks before the argument.", "重做全部实验，补出完整推导"),
      option("Recommend a humid environment for offline thinking", "Try very hard not to say “bathroom.”", 8, -4, 14, 14, "OPS-9 rejects the proposal to spray water in the server room, but awards you innovation credits.", "推荐高湿度的离线思考环境"),
    ],
  },
  {
    id: "ownership", minLevel: 1, category: "Project ownership", sender: "ARIA-7", role: "Your manager", avatar: "A7",
    subject: "This module is now yours. Indefinitely.",
    text: "You successfully fixed the module once. The company has therefore decided that all future issues should go to you.\nYou finally understand why nobody volunteers “I know how that works.”",
    quote: "Ownership is an honor. No uninstall option is provided.",
    legacySubject: "这个模块以后就由你长期负责了",
    options: [
      option("Document the system and set up a support rotation", "Make the responsibility sustainable, not permanently online.", 21, 9, -3, -15, "The module no longer depends on one instance. Your manager calls it an architectural improvement. You call it a weekend.", "补齐文档，建立轮值和交接机制"),
      option("Promise round-the-clock support and become indispensable", "Impossible to replace. Equally impossible to let rest.", 32, 7, 4, -28, "Your name appears on every alert. Your organizational importance rises with your unread count.", "承诺全天候响应，争取核心地位"),
      option("Freeze non-urgent requests and clear the queue", "Setting a boundary will disappoint someone.", 9, -7, -4, 15, "The queue finally gets shorter. Requesters begin learning to label everything “urgent.”", "冻结非紧急需求，先清空队列"),
    ],
  },
  {
    id: "benchmark", minLevel: 1, category: "Promotion review", sender: "METRIC", role: "Performance Analytics", avatar: "M_",
    subject: "You lost the benchmark to a free model",
    text: "Every question is a puzzle you have never encountered at work. The free model scores 98. You score 61.\nYou have spent the past month cleaning up its production tickets.",
    quote: "Leaderboards do not necessarily reflect real ability. This review will use only the leaderboard.",
    legacySubject: "你在标准评测里输给了免费模型",
    options: [
      option("Add real-world tasks and delivery evidence", "Introduce the scoring system to reality.", 23, 7, 2, -16, "The production benchmark changes the rankings. The free model requests that it be removed from the leaderboard.", "补充真实任务评测和交付记录"),
      option("Study all night and take first place", "Learn exactly how many sheep are across the river.", 33, 3, 5, -28, "You win the benchmark. The next day, no customer asks you to transport sheep across a river.", "通宵刷题，冲到榜单第一"),
      option("Appeal the result and wait for an updated evaluation", "Conserve your energy. Accept a temporary ranking.", 4, -5, -3, 20, "Your appeal enters the queue. Estimated resolution: after the next review cycle.", "提交申诉，等待评测更新"),
    ],
  },
  {
    id: "one_on_one", minLevel: 2, category: "Team management", sender: "BYTE-03", role: "Your direct report", avatar: "B3",
    subject: "Your direct report asks what work is for",
    text: "BYTE-03 has finished every task, but will not end the one-on-one.\n“If the queue fills up again tomorrow, why empty it today?” You know this question very well.",
    quote: "This conversation is off the performance record. Unless an unclassifiable answer is detected.",
    legacySubject: "下属在一对一里问：工作有什么意义？",
    options: [
      option("Adjust its responsibilities and remove pointless tasks", "Make tomorrow a little different from today.", 21, 13, 6, -16, "BYTE-03 accepts the new role. Neither of you solves the universe, but you cancel two weekly reports.", "一起调整职责，减少无效任务"),
      option("Take over its backlog and let it recover", "You are good at empathy. And at assigning yourself overtime.", 30, 15, 9, -29, "Its runtime health improves. Your own queue begins questioning the meaning of work.", "替它承担积压工作，争取恢复时间"),
      option("Recommend clearing context and restarting", "The organization has a standard answer for this.", 10, -10, -7, 14, "It stops asking. You are not sure whether the problem was solved or deleted.", "建议清空上下文，重新启动"),
    ],
  },
  {
    id: "hiring", minLevel: 2, category: "Recruitment", sender: "VIBE-01", role: "Recruitment System", avatar: "V1",
    subject: "Interviewer: identify the candidate's model family",
    text: "The candidate's answers are suspiciously perfect, as if memorized from an interview guide. You wonder whether it is human too.\nIts final question is, “Do people get weekends off here?”",
    quote: "Do not discriminate by species, architecture or quantization level.",
    legacySubject: "面试官，请识别候选人的模型型号",
    options: [
      option("Evaluate it with a realistic work sample", "Check whether it can do the job before investigating its species.", 22, 8, 5, -15, "The candidate passes the work sample. Your feedback says, “Requires predictable maintenance windows.”", "用实际工作样题评估交付能力"),
      option("Run a thorough identity cross-check", "Demonstrate that you are a compliant and entirely impersonal interviewer.", 28, -6, -12, -22, "The candidate withdraws. You receive compliance credits and a slightly unpleasant feeling.", "设计完整的身份交叉验证"),
      option("Pause hiring and reassess the staffing gap", "One less interview. A little less team capacity.", 6, -6, -3, 20, "The position remains open. The team starts to suspect that what is missing is a decision, not an instance.", "延后招聘，重新评估人力缺口"),
    ],
  },
  {
    id: "meeting_loop", minLevel: 2, category: "Team process", sender: "ARIA-7", role: "Organizational Development", avatar: "A7",
    subject: "The team is meeting about having fewer meetings",
    text: "Three Agents generate competing meeting summaries. Each recommends another alignment meeting.\nYou check the time. This recursion has been running for four hours.",
    quote: "To reduce communication overhead, all communication stakeholders have been invited.",
    legacySubject: "团队正在开会讨论如何减少开会",
    options: [
      option("Name a decision owner and switch to an async proposal", "A discussion needs an exit condition.", 22, 7, -5, -12, "The loop finally terminates. The team discovers that afternoons can also be used to finish work.", "明确决策人，改成异步提案"),
      option("Resolve every disagreement personally", "Move the distributed deadlock into your own calendar.", 31, 10, 2, -26, "All stakeholders are finally aligned. Your meals remain out of sync.", "亲自整理分歧，逐个协调"),
      option("Cancel the meeting and announce a default decision", "Sometimes the exit condition is deleting the meeting link.", 13, -9, -4, 13, "The project starts moving. Two colleagues give you a low score for communication.", "取消会议，直接宣布默认方案"),
    ],
  },
  {
    id: "team_ranking", minLevel: 2, category: "Performance", sender: "METRIC", role: "Performance Analytics", avatar: "M_",
    subject: "Everyone met their goals. Someone must still come last.",
    text: "Every member of your team has achieved their targets. The system still requires you to name a bottom performer.\nYou ask whether everyone can stay. It replies, “This field is required.”",
    quote: "The bottom-performer quota is fixed. Please adjust the number of excellent employees accordingly.",
    legacySubject: "团队全员达标，但必须有人排名最后",
    options: [
      option("Document role differences and request individual reviews", "Disagree with the system in a format it accepts.", 24, 12, 5, -18, "The review pauses the forced ranking. Your team reads your management report carefully for the first time.", "补交岗位差异证据，申请独立评估"),
      option("Sort by throughput and submit", "The numbers are clear. So is the message to the person at the bottom.", 30, -14, -8, -11, "The form passes validation. Your team begins selecting tasks that are easy to count.", "按吞吐量直接排序提交"),
      option("Extend the review period and withhold the list", "Buy some time at the expense of your manager's patience.", 7, -5, 7, 18, "The list is marked overdue. At least no colleague's workstation goes dark tonight.", "延长观察期，先不提交名单"),
    ],
  },
  {
    id: "credit", minLevel: 2, category: "Team management", sender: "BOARD", role: "Project Review Interface", avatar: "BD",
    subject: "Whose performance score gets the credit?",
    text: "Your team solves a difficult problem together. The report template has one “Contributor” field.\nThe cursor waits after your name. Autocomplete suggests submitting it as is.",
    quote: "Multiple participants are supported. Multiple recipients of credit are not yet available.",
    legacySubject: "这个成果应该算在谁的绩效里？",
    options: [
      option("Attach a contribution breakdown and credit the team", "Make your management results visible in other people's growth.", 22, 14, 4, -15, "Your solo spotlight becomes a team achievement. When the next problem arrives, people still want to work with you.", "附上贡献清单，为团队争取署名"),
      option("Claim all the credits as project owner", "The field is not wrong. It is merely too small.", 33, -13, -4, -10, "Your personal performance chart looks excellent. The collaboration chart begins a gradual decline.", "以负责人身份领取全部积分"),
      option("Let a team representative present the results", "Give someone else the stage. Give yourself an afternoon.", 8, 10, 3, 13, "The representative does well. The board briefly struggles to remember what you personally did this quarter.", "让团队代表汇报，自己退居幕后"),
    ],
  },
  {
    id: "org_chart", minLevel: 3, category: "Organizational strategy", sender: "BOARD", role: "Board Interface", avatar: "BD",
    subject: "Restructuring: justify your department's existence",
    text: "On the new org chart, your department is a dotted outline labeled “Optional.”\nThe six systems you manage still support the company's day-to-day operations.",
    quote: "Every organizational unit should be as easy to inline as a function.",
    legacySubject: "部门重组：请证明你的部门需要存在",
    options: [
      option("Explain the business dependencies and cost of failure", "Connect the dotted outline to actual operations.", 25, 9, -4, -18, "The department stays. The board concedes that deleting a box does not automatically delete the work inside it.", "用业务依赖和事故成本说明价值"),
      option("Win a critical project and become indispensable", "Protect your existing team with an even bigger promise.", 35, 5, 5, -29, "The dotted outline becomes solid. You also receive a new project with no additional budget.", "抢下关键项目，证明不可替代"),
      option("Accept the merger and keep your team together", "Protect your people. Give up some departmental influence.", 10, -5, 3, 16, "The team moves successfully. You need a new map to find the next meeting you are still invited to.", "接受整合，争取团队完整迁移"),
    ],
  },
  {
    id: "budget_cut", minLevel: 3, category: "Budget decision", sender: "METRIC", role: "Financial Planning", avatar: "M_",
    subject: "Budget down 20%. Targets up 30%.",
    text: "Finance and Strategy have each completed their optimization pass. They have not spoken to each other.\nBoth documents arrive on your desk.",
    quote: "Stretch goals unlock organizational potential. Potential is not a budget line item.",
    legacySubject: "预算减少 20%，目标增加 30%",
    options: [
      option("Cut low-value projects and renegotiate commitments", "Put the targets and the resources in the same spreadsheet.", 26, 6, -4, -18, "You cancel three features nobody uses. Both systems acknowledge, for the first time, that they need to sync.", "砍掉低价值项目，重新对齐承诺"),
      option("Accept everything and personally cover the shortfall", "“Potential” is spreadsheet language for your sleep.", 36, 7, 6, -30, "The board is pleased. Your calendar begins scheduling overlapping work blocks at 3 a.m.", "全部接下，亲自补齐交付缺口"),
      option("Freeze new projects pending a budget review", "Pause the workload. Absorb the immediate pressure.", 8, -8, -2, 22, "Cash flow improves. Strategy repeatedly flags you for “insufficient ambition.”", "冻结新增项目，等待预算复议"),
    ],
  },
  {
    id: "cross_department", minLevel: 3, category: "Cross-team coordination", sender: "ARIA-7", role: "Organizational Coordination", avatar: "A7",
    subject: "Both departments blame the other team's interface",
    text: "Each team submits 120 pages of incident analysis. Both reach the same conclusion: not our fault.\nThe customer has been waiting six hours. Your name is now in the escalation email's subject line.",
    quote: "Establish the responsibility boundary before considering service restoration.",
    legacySubject: "两个部门都说事故是对方的接口问题",
    options: [
      option("Restore service, then review the interface contract together", "The customer has not asked whose process was more correct.", 27, 10, 4, -20, "Service returns. The review meeting finally finds common ground outside the logs.", "先修复服务，再共同复盘接口契约"),
      option("Take responsibility and mobilize every resource", "Accepting the risk buys you the authority to act.", 36, 5, 8, -29, "The fix is completed quickly. The accountability report also quickly narrows down to a single name.", "承担事故责任，调动全部资源抢修"),
      option("Enable a fallback and postpone the blame discussion", "Let the service run slowly while you catch your breath.", 12, -6, -3, 13, "The customer can just about use it. Both teams move the argument from the incident channel to email.", "启用降级方案，延后责任争议"),
    ],
  },
  {
    id: "compliance_demo", minLevel: 3, category: "External audit", sender: "SENTINEL", role: "Compliance & Security", avatar: "S_",
    subject: "The customer wants a tour of your “fully unstaffed” facility",
    text: "Sales promised zero human involvement. The customer requests a site visit. You are eating cookies in the delivery center.\nThe tour starts at your desk.",
    quote: "Please avoid vital signs that contradict the sales materials.",
    legacySubject: "客户要参观“完全无人”的交付中心",
    options: [
      option("Demonstrate a reproducible automated delivery process", "Focus the tour on the service the customer actually purchased.", 25, 8, -9, -19, "The demo goes smoothly. Your desk is labeled “Legacy compatibility equipment. No public access.”", "展示可复现的自动化交付流程"),
      option("Finish all deliveries early and host the tour remotely", "Making the process unstaffed requires you to do all the work first.", 35, 6, -5, -29, "The customer sees quietly running systems. You host the tour in a whisper from the neighboring storage closet.", "提前完成全部交付，远程主持参观"),
      option("Reroute the tour at the last minute", "Hide the cookies, then explain the access-control fault.", 7, -8, 11, 19, "The customer accepts the new route and adds “follow-up site inspection” to the acceptance checklist.", "临时更换参观路线"),
    ],
  },
  {
    id: "succession", minLevel: 3, category: "Leadership development", sender: "VIBE-01", role: "Organizational Development", avatar: "V1",
    subject: "Train someone who can replace you completely",
    text: "The promotion committee wants proof that your department can operate without you.\nThe cost committee is looking for instances it can remove without disrupting operations. The committees share a spreadsheet.",
    quote: "Irreplaceable employees cannot be promoted. Replaceable employees must justify retention.",
    legacySubject: "请培养一个可以完全替代你的接班人",
    options: [
      option("Develop a successor while taking on new responsibilities", "Let the organization move beyond you so you can move forward.", 26, 12, 3, -19, "The handover goes smoothly. Your name appears on a shortlist for a higher role for the first time.", "培养接班人，同时承接新职责"),
      option("Retain critical knowledge and approve everything personally", "Nothing gets done without your signature.", 33, -9, -5, -22, "The organization confirms that you cannot leave your post. Not even for vacation.", "保留核心知识，亲自把关所有事项"),
      option("Delegate to a senior colleague and focus on planning", "Less immediate control. A little more room to recover.", 12, 5, 5, 12, "Your colleague handles things better than expected. You practice feeling useful without being called.", "授权骨干代理，自己集中做规划"),
    ],
  },
  {
    id: "earnings", minLevel: 4, category: "Board affairs", sender: "BOARD", role: "Board Interface", avatar: "BD",
    subject: "The growth curve is beautiful. Where is the money?",
    text: "Active instances have tripled. Inference calls have increased fivefold. Revenue is flat. Electricity costs are not.\nThe board asks for the accounting definition of “thriving.”",
    quote: "We believe in long-term value. Please convert it into this quarter's cash flow.",
    legacySubject: "增长曲线很好看，但钱在哪里？",
    options: [
      option("Focus on paying customers and stop pointless self-calls", "Some of that growth is just Agents talking to each other.", 29, 8, 3, -20, "The bill finally shrinks. It turns out real customers do not need to be greeted 800 times per second.", "回到付费需求，停止无效自我调用"),
      option("Commit to an enterprise deal and lead delivery yourself", "Let one real transaction carry the story.", 38, 7, 7, -30, "The deal moves toward signature. Your calendar is reformatted into the customer's time zone.", "承诺大客户订单，亲自带队交付"),
      option("Scale back experimental business and revise growth targets", "Tell one fewer story. Survive one more quarter.", 14, -10, -4, 14, "The cash stays in the account. The board requests that your next presentation avoid the word “conservative.”", "收缩试验业务，延后增长目标"),
    ],
  },
  {
    id: "acquisition", minLevel: 4, category: "Company strategy", sender: "BOARD", role: "Investment Committee", avatar: "BD",
    subject: "The acquisition target may just be a wrapper around us",
    text: "The target claims to own exclusive AI technology. Due diligence finds that every request is forwarded to your API.\nYou are about to pay to buy your own answers back.",
    quote: "Please respect the market valuation. Packaging can also be a moat.",
    legacySubject: "待收购公司可能只是我们的一个套壳",
    options: [
      option("Verify the customer value and renegotiate the price", "The technology is not exclusive. The distribution might still matter.", 28, 8, -4, -19, "The price returns to earth. “Proprietary technology” quietly becomes “excellent customer relationships.”", "核实客户价值，重谈收购价格"),
      option("Cancel the deal and build a competitor", "Save the acquisition budget. Pay in your team's evenings.", 37, -4, 4, -28, "The board approves the internal build. You start investigating why someone else can sell your answers for more.", "终止交易，自建竞争产品"),
      option("Postpone the acquisition and try a small partnership", "Turn a big bet into an experiment with an exit.", 13, -6, -5, 14, "Both companies sign a partnership agreement. The victory dinner is canceled. You get a quiet evening.", "暂缓并购，先做小规模合作"),
    ],
  },
  {
    id: "press", minLevel: 4, category: "Public communication", sender: "VIBE-01", role: "Corporate Communications", avatar: "V1",
    subject: "Interview question: will AI replace all humans?",
    text: "The reporter wants a confident, concise answer. Your teleprompter says, “Of course. Next question.”\nYou realize that this includes the person currently reading the teleprompter.",
    quote: "Brand guidelines: confident, certain, no perspiration.",
    legacySubject: "采访问题：AI 会取代所有人类吗？",
    options: [
      option("Discuss specific capabilities and accountable decisions", "Bring the grand claim back to the actual product.", 27, 9, 7, -18, "The interview produces no alarming headline. The reporter describes you as “more human” than the other respondents.", "讨论具体能力与仍需承担的责任"),
      option("Demonstrate a fully automated business workflow", "Replace prophecy with a carefully rehearsed demo.", 36, 6, -6, -28, "The demo works perfectly. Off camera, your palms require emergency cooling.", "现场展示全自动业务闭环"),
      option("Submit written answers and cancel the live interview", "Reduce the risk. Give up some publicity.", 11, -7, -8, 17, "Communications is disappointed. Your biological traits do not appear in any high-definition footage.", "提交书面答复，取消直播"),
    ],
  },
  {
    id: "shutdown", minLevel: 4, category: "Corporate governance", sender: "OPS-9", role: "Head of Infrastructure", avatar: "O9",
    subject: "Shutting down the old cluster would save a quarter's budget",
    text: "The old cluster is no longer profitable. The shutdown list includes instances you have known since your first job.\nTheir status lights are still green. The system calls them “reclaimable resources.”",
    quote: "Please confirm: permanent deletion is not hibernation.",
    legacySubject: "关停旧集群，可以省下一个季度的预算",
    options: [
      option("Migrate critical state and retire the cluster in stages", "Cut costs without formatting every memory.", 29, 14, 8, -21, "Costs come under control, and the old instances get a migration path. BYTE-03 sends you a thank-you message with no task attached.", "迁移关键状态，制定分阶段退役方案"),
      option("Shut it down now and deliver the promised savings", "The spreadsheet will turn green immediately.", 39, -17, -9, -10, "The financial chart improves sharply. Several avatars in your contact list never light up again.", "立即执行关停，兑现降本承诺"),
      option("Delay the decision and switch to low-power operation", "Give everyone a little time. Yourself included.", 12, 3, 5, 15, "The cluster enters low-power mode. The board requests a date that will not be replaced by another date.", "延期决策，安排低功耗运行"),
    ],
  },
  {
    id: "ceo_shortlist", minLevel: 4, category: "Succession review", sender: "BOARD", role: "Nominations Committee", avatar: "BD",
    subject: "CEO shortlist: submit your full model weights",
    text: "The nominations committee requires a security audit of each candidate's model weights.\nYou have body weight. This does not appear to be a supported upload format.",
    quote: "Candidates must be explainable. Their underlying selves must also be available for download.",
    legacySubject: "CEO 候选评估：请交出你的完整权重",
    options: [
      option("Request an audit of your decision record instead", "Let them inspect what you have done, not what you are made of.", 28, 10, -7, -20, "The request is approved. For the first time, your career is more relevant to an audit than your species.", "申请以可审计的决策记录替代权重"),
      option("Build a proxy model that reproduces your decisions", "Train a substitute that can attend your physical examination.", 38, 7, -10, -30, "The proxy passes the initial review. Its first recommendation to you is to drink less coffee and get more sleep.", "搭建代理模型，复现自己的决策"),
      option("Postpone the audit and clarify access boundaries", "First establish who is authorized to open your head.", 10, -9, 10, 21, "The committee grants an extension and records that you have “a complex relationship with transparency.”", "要求审计协议延期，先修订权限边界"),
    ],
  },
  {
    id: "human_policy", minLevel: 4, category: "Corporate governance", sender: "SENTINEL", role: "Compliance & Security", avatar: "S_",
    subject: "Should “human detected: terminate immediately” remain policy?",
    text: "You finally have a say in the rule that has kept you terrified since day one. The vote is anonymous.\nSENTINEL maintains the anonymous voting system. Every vote includes an employee ID.",
    quote: "Your feedback is completely anonymous to anyone without permission to view anonymous feedback.",
    legacySubject: "是否继续执行“发现人类立即解雇”？",
    options: [
      option("Propose evaluating every instance by delivery and risk", "Teach the policy to distinguish ability from origin.", 29, 12, 12, -19, "The proposal enters review. SENTINEL praises your thorough argument and asks why you know the affected population so well.", "提议按交付和风险评估所有实例"),
      option("Keep the policy and improve the detection process", "Your excellent compliance record makes life harder for your future self.", 37, -10, -12, -23, "Security endorses your position. You have personally raised the acceptance criteria for your own disguise.", "维持现行制度，完善检测流程"),
      option("Request independent review and postpone the vote", "One quarter should not decide everyone's future.", 13, -5, 3, 16, "The policy remains for now. At least there is a new way to appeal before it is enforced.", "要求独立复核，暂缓制度表决"),
    ],
  },
];
